services:
  cc-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cc-adapter
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
