services:
  cc-adapter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cc-adapter
    restart: always
    stop_grace_period: 10m30s
    ports:
      - "${CC_ADAPTER_PORT:-8080}:${CC_ADAPTER_PORT:-8080}"
    environment:
      - CC_ADAPTER_PORT=${CC_ADAPTER_PORT:-8080}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
